[db]
dsn = "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.eu-paris-1.oraclecloud.com))(connect_data=(service_name=gbf0e72c4e487a3_cosmetics_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"
user = "tarik"
password = "CamilaKhaled_2025"